name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up the Python version based on the matrix
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies, including pylint
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
        
      # Run pylint on all Python files
      - name: Lint Python code with pylint
        run: |
          pylint $(git ls-files '*.py')
