name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up the specific Python version from the matrix
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install all necessary dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      # Step 4: Run pylint to analyze the code
      - name: Analyse the code with pylint
        run: |
          pylint $(git ls-files '*.py')
