name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.10'
        environment-file: environment.yml
        mamba-version: "*"
        auto-activate-base: false
        activate-environment: <environment_name> # Replace <environment_name> with the name from environment.yml

    - name: Show Conda info
      run: |
        conda info
        conda list
        which python
        python --version

    - name: Lint with flake8
      run: |
        echo "Running critical flake8 checks..."
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "Running stylistic flake8 checks (won't fail build)..."
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
